site_name: sever-web
site_description: Server-side of pomodoro panel
repo_url: https://github.com/sterenczak-marek/server
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/sterenczak-marek">sterenczak-marek</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
